---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-waofed-bitmedia-co-jp-v1beta1-estimator
  failurePolicy: Fail
  name: mestimator.kb.io
  rules:
  - apiGroups:
    - waofed.bitmedia.co.jp
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - estimators
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-waofed-bitmedia-co-jp-v1beta1-estimator
  failurePolicy: Fail
  name: vestimator.kb.io
  rules:
  - apiGroups:
    - waofed.bitmedia.co.jp
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - estimators
  sideEffects: None
