openapi: 3.1.0
info:
  title: "WAO Estimator"
  description: ""
  version: 0.1.0
  termsOfService: https://github.com/Nedopro2022/wao-estimator
  contact:
    url: "https://github.com/Nedopro2022/wao-estimator/issues"
  license:
    name: "Apache-2.0"
    url: "https://github.com/Nedopro2022/wao-estimator/blob/main/LICENSE"
servers:
  - url: ""
tags:
  - name: Estimator
    description: ""
paths:
  /namespaces/{ns}/estimators/{name}/values/powerconsumption:
    post:
      tags:
        - Estimator
      summary: Send a power consumption estimate request.
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PowerConsumption"
      responses:
        "200":
          description: Estimation completed successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PowerConsumption"
        "400":
          description: Invalid PowerCunsumption request supplied.
        "401":
          description: Unauthorized.
        "404":
          description: Estimator not found.
        "500":
          description: Unable to operate.
    parameters:
      - name: ns
        in: path
        description: Namespace that the Estimator resource is deployed.
        required: true
        schema:
          type: string
          example: default
      - name: name
        in: path
        description: Name of the Estimator resource.
        required: true
        schema:
          type: string
          example: default
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    PowerConsumption:
      type: object
      required:
        - cpu_milli
        - num_workloads
      properties:
        cpu_milli:
          type: integer
          examples:
            - 0
            - 500
            - 2000
          description: The amount of CPUs required by each workload.
        num_workloads:
          type: integer
          examples:
            - 0
            - 1
            - 15
          description: The amount of workloads have to be allocated.
        watt_increases:
          type: array
          items:
            type: number
            format: double
          examples:
            - []
            - [5.0]
            - [5.0, 10.0, 15.0, 20.0, 15.0]
          description: The estimated power increase per workload.
