# permissions for end users to edit estimators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: estimator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: wao-estimator
    app.kubernetes.io/part-of: wao-estimator
    app.kubernetes.io/managed-by: kustomize
  name: estimator-editor-role
rules:
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - estimators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - estimators/status
  verbs:
  - get
