---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - estimators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - estimators/finalizers
  verbs:
  - update
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - estimators/status
  verbs:
  - get
  - patch
  - update
