name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  image:
    name: Push container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/wao-estimator-controller
          tags: |
            # v1.2.3-rc.4
            type=semver,pattern={{raw}}
            # 1.2.3-rc.4
            type=semver,pattern={{version}}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: "build wao-estimator.yaml"
        run: REGISTRY=ghcr.io/${GITHUB_REPOSITORY_OWNER,,} ./hack/dist-manifests.sh
      - name: "build estimator-cli"
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags "-s -w" ./pkg/cmd/estimator-cli/
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            wao-estimator.yaml
            estimator-cli
